### ISSUE TITLE
normalized-data

### ISSUE THREAD

**Issue by hedgehog9014** [mskcc/RNAseqDB#2]
I'm looking at the processed files stored here: https://github.com/mskcc/RNAseqDB/tree/master/normalized-data
I'm wondering why the file names contain the terms 'rsem' and 'fpkm'.  Could you please confirm how they were created (i.e. from the raw sra/fastq files or from the level 3 TCGA/GTEx data).  I understand that they were batch corrected by ComBat.  Many thanks

**Comment by qwangmsk** [comment]
Because we ran two quantification tools: RSEM and FeatureCounts. The term 'rsem' indicates the files were created using RSEM instead of FeatureCounts. 

Both 'fpkm' and 'tpm' are popular measures of expression. They can be produced using either RSEM or FeatureCounts. The term 'fpkm' indicates expression is measured using FPKM. 

All these data were obtained by applying our pipeline to raw sra/fastq files.
